name: CI/CD

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update HTML
        run: |
          echo "<h1>Hello</h1>" > index.html
          
      - name: Commit and push changes
        run: |
          git config --global user.name "duong"
          git config --global user.email "daoduong2k1k.vk@gmail.com"
          git add index.html
          git commit -m "Update HTML"
          git push
